### PR TITLE
Bump aeson. Update version and changelog.

### PR DESCRIPTION
**Pull request by jprider63**
I did a bigger `aeson` bump so we don't have to keep updating it. @denibertovic, can you upload to hackage?

### CODE REVIEW

**Comment by denibertovic** [comment]
@jprider63 I restarted the travis job that was failing. 

This looks good to me but I think we should do a major version bump because of the first line in the changelog.

**Comment by jprider63** [comment]
Ok, makes sense to me.

**Comment by denibertovic** [comment]
I'll merge and update separately. Thanks!

**Comment by denibertovic** [comment]
@jprider63 Uploaded to hackage.

**Comment by jprider63** [comment]
👍

**Pull request merged**
