### PR TITLE
Image deletion implementation

### PR DESCRIPTION
**Pull request by SkyWriter**

### CODE REVIEW

**Comment by SkyWriter** [comment]
@denibertovic thank you for your work on the project and please let me know if I need to make any additional changes to the PR!

**Comment by jprider63** [comment]
Thanks for the PR @SkyWriter! I have a few comments. 

- It looks like you describe `DeleteOpts` and `defaultDeleteOpts` in the documentation, but they don't exist. Can you add them (even if you don't include any options, ex `data DeleteOpts = DeleteOpts`)? There are options that could be included in the future like `force` and `noprune`, and it'd be preferable if the API doesn't need to change. 
- Can you add two integration tests? One where the image id exists and one where it doesn't?

**Comment by denibertovic** [comment]
Hey @SkyWriter thanks for the contribution!  I agree with what @jprider63 wrote above but would like to add that we already have `DeleteOpts` and `defaultDeleteOpts` for the container delete endpoint. These seem to be container specific values so we would likely need to add new Opts for the Image deletion endpoint. @jprider63 does it make sense to rename the container delete opts at this point ie. ContainerDeleteOpts and ImageDeleteOpts?

**Comment by SkyWriter** [comment]
Sounds fair. Here's what's on my list so far:
- [ ] Introduce image deletion options
- [ ] Make up a couple of integration tests

I'm voting for more specific `ContainerDeleteOpts` and `ImageDeleteOpts` Deni proposed. Even though it means API has to change, it's better done sooner than later. Please let us know, if that's something you'd go for, @jprider63. Thanks!

**Comment by SkyWriter** [comment]
Gentlemen, would you care taking a look now? Thanks!

**Comment by jprider63** [comment]
Looks good! Thanks @SkyWriter! I'll merge soon unless @denibertovic has further feedback.

**Comment by denibertovic** [comment]
Thanks @SkyWriter @jprider63 :cake:

**Pull request merged**
