### PR TITLE
Add SSL capability

### PR DESCRIPTION
**Pull request by ababkin**
Some docker installations require SSL connection to docker daemon. (e.g. using docker-machine)
This PR adds sufficient capabilities.

### CODE REVIEW

**Comment by denibertovic** [comment]
@ababkin Thank you for the contribution! This is really awesome! :+1: 

To be clear though this PR only adds the ability for the connection from the client to the daemon to be encrypted via ssl, but does not touch on the client/server tls auth, right?

**Comment by ababkin** [comment]
Yes, I only needed this in order to connect to the docker remote api and it looks like the docker daemon started by docker-machine requires SSL to communicate.

**Comment by denibertovic** [comment]
@ababkin awesome. Thanks once again. I'm merging this and I'll do a release later today (tomorrow the latest). :)

**Comment by denibertovic** [comment]
@ababkin It's released on hackage. Sorry for the delay.

**Pull request merged**
