### PR TITLE
Update to work with stack lts-9.4

### PR DESCRIPTION
**Pull request by locallycompact**
Updated to work with new http-client library and lts-9.4.

I got rid of the other stack files because the resolvers didn't match the filenames anyway.

Edit: I notice from the CI that the version number in the stack-$version.yaml files was intended to represent ghc version and not resolver version, in which case I got rid of them for the reason that that's very confusing and I don't understand why that would be useful to have around.

### CODE REVIEW

**Comment by jprider63** [comment]
Thanks for the pull request! 

The changes look good to me, but we should maintain backwards compatibility. Can you add back the stack yaml files you deleted and rename your newly created one to `stack-8.0.2.yaml` (and add version 8.0.2 to the travis file)? Then you can add a macro that uses the previous exception pattern matching if http-client is less than version 0.5.0.

**Comment by locallycompact** [comment]
If someone wants to use an old resolver wouldn't they just use the already published versions of the library? Why complicate development?

**Comment by jprider63** [comment]
We should prioritize usability for the library's users. Searching through previous versions for one that is compatible is an easily avoided pain point (especially for non-stack users).

**Comment by locallycompact** [comment]
I don't think that's easily avoided at all. Isn't preprocessing all library API changes that occur is a strategy that surely can't extend beyond a handful of potential combinations before it becomes combinatorially explosive to ensure all variants build?

**Comment by jprider63** [comment]
Hypothetically sure, but this is a 5 line change. If it gets too complicated in the future, we can drop support for previous versions (I doubt this will happen in practice though). 

Another reason backwards compatibility is preferred is that any bug fixes we make in the future will be available for previous versions of ghc and http-client. 

I can implement the macro if you don't want to.

**Comment by denibertovic** [comment]
@locallycompact I agree with @jprider63 on this. We should keep backwards compatibility for as long as it makes sense. And this doesn't seem like a huge change to support for now.

**Comment by locallycompact** [comment]
I really don't find this whole thing coherent at all. Why label stack-$X.yaml files by compiler version? Who benefits from this?

**Comment by jprider63** [comment]
I just added backwards compatibility to this in #35. 

I attempted to attribute @locallycompact, but I don't know your email address. If you let me know what it is, I can fix it so it links to your account (I can also remove the attribution if you prefer).

**Comment by locallycompact** [comment]
locallycompact@gmail.com, thanks

**Comment by jprider63** [comment]
Updated. Thanks again!

**Comment by denibertovic** [comment]
This has been merged as part of #35. Closing.

**Pull request closed without merging**
