### PR TITLE
Fixes BindPort parsing and adds a test case

### PR DESCRIPTION
**Pull request by jprider63**

### CODE REVIEW

**Comment by jprider63** [comment]
@thoaionline can you confirm this fixes #80 and the added [test case](https://github.com/denibertovic/docker-hs/pull/81/files#diff-5f3fa842920120f83b0bc39ed88db1368f078a75219000028a89a2dd4fec25f4R213) is representative of the JSON response you received?

**Comment by thoaionline** [comment]
will check this out over the weekend :)

**Comment by jprider63** [comment]
It's been a little while, so I'm going to merge this. @denibertovic, can you release on hackage?

**Comment by denibertovic** [comment]
Done.

Thanks @jprider63 @thoaionline

**Pull request merged**
