### PR TITLE
Streaming API w/ dev merged

### PR DESCRIPTION
**Pull request by jprider63**
#13

### CODE REVIEW

**Comment by denibertovic** [comment]
Hey sorry for the delay. I'd take a look at this by the end of the week and hopefully get it merged.

**Comment by jprider63** [comment]
Great thanks!

**Comment by denibertovic** [comment]
@jprider63 This is awesome! Thank you! :cake: I'm going to merge it. I know why the tests are failing on travis but I'll fix that in master once merged.

**Comment by denibertovic** [comment]
@jprider63 released on hackage.

**Comment by jprider63** [comment]
👍

**Pull request merged**
