### PR TITLE
fix null NetworkSettings.Ports

### PR DESCRIPTION
**Pull request by backuitist**

### CODE REVIEW

**Comment by jprider63** [comment]
Thanks for the PR @backuitist! Do you have an example JSON test case that's failing? 

I'm somewhat inclined to leave the type unchanged and change the [PortBinding instance](https://github.com/denibertovic/docker-hs/blob/ba31e234aad8cadedacb98fdf064fef80718f575/src/Docker/Client/Types.hs#L1159).

**Comment by denibertovic** [comment]
Hey @backuitist thanks for the PR. Do you mind adding a test for this change?

**Comment by thoaionline** [comment]
@denibertovic doesn't look like this needs a test as it's a derived type update.

This PR will fix #80

**Comment by jprider63** [comment]
Closing in favor of #81 which doesn't change the types/API.

**Pull request closed without merging**
