### PR TITLE
Upgrade dependencies, add deleteContainer function

### PR DESCRIPTION
**Pull request by Helkafen**
Also added some basic tests, and a stack file for deterministic builds.

### CODE REVIEW

**Comment by denibertovic** [comment]
LGTM. Thanks for the contribution! :+1:

**Comment by denibertovic** [comment]
@Helkafen cabal upload complains that I need to specify an upper bound for base. Is there any reason why setting < 4.8 was removed?

**Comment by Helkafen** [comment]
GHC 7.10 ships with base-4.8 (https://ghc.haskell.org/trac/ghc/wiki/Migration/7.10), but yes maybe it is more correct to specify an upper bound :)
A travis build could help detect this kind of issues. I could contribute that if you like.

**Comment by denibertovic** [comment]
@Helkafen It would need to be <= 4.8 then right? cause currently I've specified < 4.8. 

And yes Travis would be nice. :)

**Comment by Helkafen** [comment]
The base library can have minor releases, so < 4.9 would be more future-proof.
Ok for travis!

**Comment by denibertovic** [comment]
Ok. Fixed to < 4.9.

**Pull request merged**
