### PR TITLE
get all containers and images

### PR DESCRIPTION
**Pull request by j4**
Add the possibility to list all containers or images.

### CODE REVIEW

**Comment by denibertovic** [comment]
Hey. Thanks for the contribution! :+1: 

One nitpick though, would it make sense to add this as a parameter to the already existing
functions: getDockerImages and getDockerContainers? Like a parameter "all" but set to False as default?

**Comment by j4** [comment]
Yes good idea

**Comment by j4** [comment]
or pass data type "rest config" ex:

```
data GetContainersParams {
limit :: Int,
all :: Boolean ...
}
```

```
defaultGetContainersPrms = ...
```

no ? The problem will arise with other services.

**Comment by denibertovic** [comment]
I only see this (ie. all=True) for the container endpoint and for the images endpoint ... perhaps we can generalize the datatype to fit both cases?

**Comment by denibertovic** [comment]
Let's merge this for now and think of a better solution later. There's been a refactoring going on for some time now but I haven't had time to tie everything together yet. No reason for this to wait.

**Comment by denibertovic** [comment]
release on hackage

**Pull request merged**
