### PR TITLE
Bump versions for http-conduit and http-types

### PR DESCRIPTION
**Pull request by jprider63**
Should fix fpco/stackage#3232, fpco/stackage#3204, and (mostly) #54. @denibertovic, can you release assuming tests pass?

### CODE REVIEW

**Comment by denibertovic** [comment]
@jprider63 I think we have to add unliftio-core to extra-deps for the 7.10 and 8.0 stack.yaml files. Right?

**Comment by jprider63** [comment]
Yes, I suppose so. 

Maybe we should have a greater version bump too since there's a minor API change.

**Comment by denibertovic** [comment]
@jprider63 I'm confused, which api change are you talking about? Don't we make sure to support http-conduit pre 2.3.0 and after 2.3.0 with the flag you introduced?

**Comment by denibertovic** [comment]
@jprider63 Ah I see what you mean. Yeah we should bump C in A.B.C. Merging.

**Pull request merged**
